# This is a basic workflow to help you get started with Actions

name: Ashboarday-Updater

# Controls when the action will run. 
on:
  # Triggered every night. Change to the frequency you desire:
  schedule:
    - cron: '0 1 * * *' # runs at 1:00 UTC everyday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updater:
    runs-on: ubuntu-latest  # Tell GitHub to use a fresh Linux virtual machine to run this workflow
    steps:
      # Check-out the repository to the virtual machine so it can analyze it:
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Signal the start
        run: echo Starting the Ashboarday Updater
        
      - name: execute py script
        run: python .dash/Ashboarday_Updater_GitHub.py
        env:  
          ash_path: '.dash/'
          
      - name: report status
        run: echo "This job's status is ${{ job.status }}."
